/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AccountType
 */
export interface AccountType {
  /**
   *
   * @type {string}
   * @memberof AccountType
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AccountType
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof AccountType
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof AccountType
   */
  type: AccountTypeTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum AccountTypeTypeEnum {
  Freelancer = 'FREELANCER',
  Employer = 'EMPLOYER',
}
