/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateJobOpeningDTO
 */
export interface CreateJobOpeningDTO {
  /**
   *
   * @type {string}
   * @memberof CreateJobOpeningDTO
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateJobOpeningDTO
   */
  description: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateJobOpeningDTO
   */
  categories: Array<CreateJobOpeningDTOCategoriesEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateJobOpeningDTOCategoriesEnum {
  It = 'IT',
  Art = 'Art',
  ConstructionWorker = 'Construction Worker',
  Foreman = 'Foreman',
  Plumber = 'Plumber',
  Carpenter = 'Carpenter',
  Electrician = 'Electrician',
  Welder = 'Welder',
  AirconRepair = 'Aircon Repair',
  GadgetRepair = 'Gadget Repair',
}
