/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EditEmployerDTO
 */
export interface EditEmployerDTO {
  /**
   *
   * @type {string}
   * @memberof EditEmployerDTO
   */
  companyName?: string;
  /**
   *
   * @type {string}
   * @memberof EditEmployerDTO
   */
  companyDescription?: string;
  /**
   *
   * @type {string}
   * @memberof EditEmployerDTO
   */
  companyLink?: string;
}
