/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EditUserDTO
 */
export interface EditUserDTO {
  /**
   *
   * @type {string}
   * @memberof EditUserDTO
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof EditUserDTO
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof EditUserDTO
   */
  bio?: string;
}
