/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserDTO } from './user-dto';
import { WorkExperienceDTO } from './work-experience-dto';

/**
 *
 * @export
 * @interface FreelancerDTO
 */
export interface FreelancerDTO {
  /**
   *
   * @type {string}
   * @memberof FreelancerDTO
   */
  id: string;
  /**
   *
   * @type {Array<WorkExperienceDTO>}
   * @memberof FreelancerDTO
   */
  workExperiences: Array<WorkExperienceDTO>;
  /**
   *
   * @type {UserDTO}
   * @memberof FreelancerDTO
   */
  user?: UserDTO;
}
