/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobApplication } from './job-application';
import { User } from './user';
import { WorkExperience } from './work-experience';

/**
 *
 * @export
 * @interface Freelancer
 */
export interface Freelancer {
  /**
   *
   * @type {string}
   * @memberof Freelancer
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Freelancer
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Freelancer
   */
  updatedAt: string;
  /**
   *
   * @type {User}
   * @memberof Freelancer
   */
  user: User;
  /**
   *
   * @type {Array<WorkExperience>}
   * @memberof Freelancer
   */
  workExperiences: Array<WorkExperience>;
  /**
   *
   * @type {Array<JobApplication>}
   * @memberof Freelancer
   */
  jobApplications: Array<JobApplication>;
}
