/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FreelancerDTO } from './freelancer-dto';
import { JobOpeningDTO } from './job-opening-dto';

/**
 *
 * @export
 * @interface JobApplicationDTO
 */
export interface JobApplicationDTO {
  /**
   *
   * @type {string}
   * @memberof JobApplicationDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof JobApplicationDTO
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof JobApplicationDTO
   */
  updatedAt?: string;
  /**
   *
   * @type {FreelancerDTO}
   * @memberof JobApplicationDTO
   */
  freelancer?: FreelancerDTO;
  /**
   *
   * @type {JobOpeningDTO}
   * @memberof JobApplicationDTO
   */
  jobOpening?: JobOpeningDTO;
  /**
   *
   * @type {string}
   * @memberof JobApplicationDTO
   */
  status?: JobApplicationDTOStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum JobApplicationDTOStatusEnum {
  Accepted = 'ACCEPTED',
  Rejected = 'REJECTED',
  UnderReview = 'UNDER REVIEW',
}
