/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Freelancer } from './freelancer';
import { JobOpening } from './job-opening';

/**
 *
 * @export
 * @interface JobApplication
 */
export interface JobApplication {
  /**
   *
   * @type {string}
   * @memberof JobApplication
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof JobApplication
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof JobApplication
   */
  updatedAt: string;
  /**
   *
   * @type {Freelancer}
   * @memberof JobApplication
   */
  freelancer: Freelancer;
  /**
   *
   * @type {JobOpening}
   * @memberof JobApplication
   */
  jobOpening: JobOpening;
  /**
   *
   * @type {string}
   * @memberof JobApplication
   */
  status: JobApplicationStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum JobApplicationStatusEnum {
  Accepted = 'ACCEPTED',
  Rejected = 'REJECTED',
  UnderReview = 'UNDER REVIEW',
}
