/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Room } from './room';
import { User } from './user';

/**
 *
 * @export
 * @interface Message
 */
export interface Message {
  /**
   *
   * @type {string}
   * @memberof Message
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof Message
   */
  content: string;
  /**
   *
   * @type {User}
   * @memberof Message
   */
  sender: User;
  /**
   *
   * @type {boolean}
   * @memberof Message
   */
  seen: boolean;
  /**
   *
   * @type {Room}
   * @memberof Message
   */
  room: Room;
}
