/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NotificationDTO
 */
export interface NotificationDTO {
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  content: string;
  /**
   *
   * @type {boolean}
   * @memberof NotificationDTO
   */
  seen: boolean;
  /**
   *
   * @type {string}
   * @memberof NotificationDTO
   */
  timeAgo: string;
}
