/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NotificationDTO } from './notification-dto';

/**
 *
 * @export
 * @interface NotificationsDTO
 */
export interface NotificationsDTO {
  /**
   *
   * @type {number}
   * @memberof NotificationsDTO
   */
  numUnread: number;
  /**
   *
   * @type {Array<NotificationDTO>}
   * @memberof NotificationsDTO
   */
  notifications: Array<NotificationDTO>;
}
