/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MessageDTO } from './message-dto';
import { UserDTO } from './user-dto';

/**
 *
 * @export
 * @interface RoomDTO
 */
export interface RoomDTO {
  /**
   *
   * @type {string}
   * @memberof RoomDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof RoomDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof RoomDTO
   */
  updatedAt: string;
  /**
   *
   * @type {Array<MessageDTO>}
   * @memberof RoomDTO
   */
  messages: Array<MessageDTO>;
  /**
   *
   * @type {Array<UserDTO>}
   * @memberof RoomDTO
   */
  participants: Array<UserDTO>;
  /**
   *
   * @type {boolean}
   * @memberof RoomDTO
   */
  hasUnseenMessages: boolean;
  /**
   *
   * @type {string}
   * @memberof RoomDTO
   */
  name?: string;
}
