/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Message } from './message';
import { User } from './user';

/**
 *
 * @export
 * @interface Room
 */
export interface Room {
  /**
   *
   * @type {string}
   * @memberof Room
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Room
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof Room
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof Room
   */
  name?: string;
  /**
   *
   * @type {Array<Message>}
   * @memberof Room
   */
  messages: Array<Message>;
  /**
   *
   * @type {Array<User>}
   * @memberof Room
   */
  participants: Array<User>;
}
