/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountType } from './account-type';
import { Notification } from './notification';
import { Room } from './room';

/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {string}
   * @memberof User
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  currentHashedRefreshToken?: string;
  /**
   *
   * @type {Array<AccountType>}
   * @memberof User
   */
  accountTypes: Array<AccountType>;
  /**
   *
   * @type {Array<Room>}
   * @memberof User
   */
  rooms: Array<Room>;
  /**
   *
   * @type {Array<Notification>}
   * @memberof User
   */
  notifications: Array<Notification>;
}
