/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  username: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserDTO
   */
  accountTypes: Array<UserDTOAccountTypesEnum>;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  employerId?: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  freelancerId?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum UserDTOAccountTypesEnum {
  Freelancer = 'FREELANCER',
  Employer = 'EMPLOYER',
}
