/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WorkExperienceDTO
 */
export interface WorkExperienceDTO {
  /**
   *
   * @type {string}
   * @memberof WorkExperienceDTO
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperienceDTO
   */
  yearsOfExperience: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperienceDTO
   */
  jobTitle: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperienceDTO
   */
  jobDescription: string;
}
