/* tslint:disable */
/* eslint-disable */
/**
 * NestJS/NextJS Template
 * API for NestJS/NextJS Template
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Freelancer } from './freelancer';

/**
 *
 * @export
 * @interface WorkExperience
 */
export interface WorkExperience {
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  updatedAt: string;
  /**
   *
   * @type {Freelancer}
   * @memberof WorkExperience
   */
  freelancer: Freelancer;
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  yearsOfExperience: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  jobTitle: string;
  /**
   *
   * @type {string}
   * @memberof WorkExperience
   */
  jobDescription: string;
}
