export enum WebSocketEvents {
  NOTIFICATIONS = 'NOTIFICATIONS',
  APPLY_JOB_OPENING = 'APPLY_JOB_OPENING',
  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',
  MESSAGES_SEEN = 'MESSAGES_SEEN',
  JOIN_ROOM = 'JOIN_ROOM',
}
